mysql: 
  url: jdbc:mysql://localhost:3306/blog_system?serverTimezone=UTC
  username: root
  password: 123456
register:
    maxCount: 5
    
spring: 
  mail:
    host: smtp.qq.com
    username: 382686267@qq.com
    password: mufesanpoinobicd
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mail:
  fromMail:
    addr: 382686267@qq.com
